#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="jobPortalDb")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertActivate_User(Activate_User instance);
  partial void UpdateActivate_User(Activate_User instance);
  partial void DeleteActivate_User(Activate_User instance);
  partial void InsertAdminTable(AdminTable instance);
  partial void UpdateAdminTable(AdminTable instance);
  partial void DeleteAdminTable(AdminTable instance);
  partial void InsertappliedJob(appliedJob instance);
  partial void UpdateappliedJob(appliedJob instance);
  partial void DeleteappliedJob(appliedJob instance);
  partial void Insertcatagory(catagory instance);
  partial void Updatecatagory(catagory instance);
  partial void Deletecatagory(catagory instance);
  partial void Insertfeed(feed instance);
  partial void Updatefeed(feed instance);
  partial void Deletefeed(feed instance);
  partial void Insertjob(job instance);
  partial void Updatejob(job instance);
  partial void Deletejob(job instance);
  partial void InsertjobSeeker(jobSeeker instance);
  partial void UpdatejobSeeker(jobSeeker instance);
  partial void DeletejobSeeker(jobSeeker instance);
  partial void InsertjobseekereducationalInfo(jobseekereducationalInfo instance);
  partial void UpdatejobseekereducationalInfo(jobseekereducationalInfo instance);
  partial void DeletejobseekereducationalInfo(jobseekereducationalInfo instance);
  partial void InsertjobSeekerProfessionalInfo(jobSeekerProfessionalInfo instance);
  partial void UpdatejobSeekerProfessionalInfo(jobSeekerProfessionalInfo instance);
  partial void DeletejobSeekerProfessionalInfo(jobSeekerProfessionalInfo instance);
  partial void Insertrecruiter(recruiter instance);
  partial void Updaterecruiter(recruiter instance);
  partial void Deleterecruiter(recruiter instance);
  partial void Insertskillsandcv(skillsandcv instance);
  partial void Updateskillsandcv(skillsandcv instance);
  partial void Deleteskillsandcv(skillsandcv instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["jobPortalDbConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Activate_User> Activate_Users
	{
		get
		{
			return this.GetTable<Activate_User>();
		}
	}
	
	public System.Data.Linq.Table<AdminTable> AdminTables
	{
		get
		{
			return this.GetTable<AdminTable>();
		}
	}
	
	public System.Data.Linq.Table<appliedJob> appliedJobs
	{
		get
		{
			return this.GetTable<appliedJob>();
		}
	}
	
	public System.Data.Linq.Table<catagory> catagories
	{
		get
		{
			return this.GetTable<catagory>();
		}
	}
	
	public System.Data.Linq.Table<feed> feeds
	{
		get
		{
			return this.GetTable<feed>();
		}
	}
	
	public System.Data.Linq.Table<job> jobs
	{
		get
		{
			return this.GetTable<job>();
		}
	}
	
	public System.Data.Linq.Table<jobSeeker> jobSeekers
	{
		get
		{
			return this.GetTable<jobSeeker>();
		}
	}
	
	public System.Data.Linq.Table<jobseekereducationalInfo> jobseekereducationalInfos
	{
		get
		{
			return this.GetTable<jobseekereducationalInfo>();
		}
	}
	
	public System.Data.Linq.Table<jobSeekerProfessionalInfo> jobSeekerProfessionalInfos
	{
		get
		{
			return this.GetTable<jobSeekerProfessionalInfo>();
		}
	}
	
	public System.Data.Linq.Table<recruiter> recruiters
	{
		get
		{
			return this.GetTable<recruiter>();
		}
	}
	
	public System.Data.Linq.Table<skillsandcv> skillsandcvs
	{
		get
		{
			return this.GetTable<skillsandcv>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="Jp.Activate_User")]
public partial class Activate_User : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Guid _Activation_Code;
	
	private string _username;
	
	private string _userType;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnActivation_CodeChanging(System.Guid value);
    partial void OnActivation_CodeChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnuserTypeChanging(string value);
    partial void OnuserTypeChanged();
    #endregion
	
	public Activate_User()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Activation_Code", DbType="UniqueIdentifier NOT NULL")]
	public System.Guid Activation_Code
	{
		get
		{
			return this._Activation_Code;
		}
		set
		{
			if ((this._Activation_Code != value))
			{
				this.OnActivation_CodeChanging(value);
				this.SendPropertyChanging();
				this._Activation_Code = value;
				this.SendPropertyChanged("Activation_Code");
				this.OnActivation_CodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string username
	{
		get
		{
			return this._username;
		}
		set
		{
			if ((this._username != value))
			{
				this.OnusernameChanging(value);
				this.SendPropertyChanging();
				this._username = value;
				this.SendPropertyChanged("username");
				this.OnusernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userType", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
	public string userType
	{
		get
		{
			return this._userType;
		}
		set
		{
			if ((this._userType != value))
			{
				this.OnuserTypeChanging(value);
				this.SendPropertyChanging();
				this._userType = value;
				this.SendPropertyChanged("userType");
				this.OnuserTypeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="Jp.AdminTable")]
public partial class AdminTable : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _Name;
	
	private string _Phone_;
	
	private string _Designation;
	
	private string _Email;
	
	private string _DefaultEmailAccountforEmail;
	
	private string _DefaultEmailPassword;
	
	private string _Address;
	
	private string _EmailSendFrom;
	
	private System.Data.Linq.Binary _Image;
	
	private string _Username;
	
	private string _Password;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPhone_Changing(string value);
    partial void OnPhone_Changed();
    partial void OnDesignationChanging(string value);
    partial void OnDesignationChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDefaultEmailAccountforEmailChanging(string value);
    partial void OnDefaultEmailAccountforEmailChanged();
    partial void OnDefaultEmailPasswordChanging(string value);
    partial void OnDefaultEmailPasswordChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnEmailSendFromChanging(string value);
    partial void OnEmailSendFromChanged();
    partial void OnImageChanging(System.Data.Linq.Binary value);
    partial void OnImageChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
	
	public AdminTable()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Name
	{
		get
		{
			return this._Name;
		}
		set
		{
			if ((this._Name != value))
			{
				this.OnNameChanging(value);
				this.SendPropertyChanging();
				this._Name = value;
				this.SendPropertyChanged("Name");
				this.OnNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Phone ]", Storage="_Phone_", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Phone_
	{
		get
		{
			return this._Phone_;
		}
		set
		{
			if ((this._Phone_ != value))
			{
				this.OnPhone_Changing(value);
				this.SendPropertyChanging();
				this._Phone_ = value;
				this.SendPropertyChanged("Phone_");
				this.OnPhone_Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Designation", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Designation
	{
		get
		{
			return this._Designation;
		}
		set
		{
			if ((this._Designation != value))
			{
				this.OnDesignationChanging(value);
				this.SendPropertyChanging();
				this._Designation = value;
				this.SendPropertyChanged("Designation");
				this.OnDesignationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultEmailAccountforEmail", DbType="VarChar(50)")]
	public string DefaultEmailAccountforEmail
	{
		get
		{
			return this._DefaultEmailAccountforEmail;
		}
		set
		{
			if ((this._DefaultEmailAccountforEmail != value))
			{
				this.OnDefaultEmailAccountforEmailChanging(value);
				this.SendPropertyChanging();
				this._DefaultEmailAccountforEmail = value;
				this.SendPropertyChanged("DefaultEmailAccountforEmail");
				this.OnDefaultEmailAccountforEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DefaultEmailPassword", DbType="VarChar(50)")]
	public string DefaultEmailPassword
	{
		get
		{
			return this._DefaultEmailPassword;
		}
		set
		{
			if ((this._DefaultEmailPassword != value))
			{
				this.OnDefaultEmailPasswordChanging(value);
				this.SendPropertyChanging();
				this._DefaultEmailPassword = value;
				this.SendPropertyChanged("DefaultEmailPassword");
				this.OnDefaultEmailPasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(50)")]
	public string Address
	{
		get
		{
			return this._Address;
		}
		set
		{
			if ((this._Address != value))
			{
				this.OnAddressChanging(value);
				this.SendPropertyChanging();
				this._Address = value;
				this.SendPropertyChanged("Address");
				this.OnAddressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmailSendFrom", DbType="VarChar(3)")]
	public string EmailSendFrom
	{
		get
		{
			return this._EmailSendFrom;
		}
		set
		{
			if ((this._EmailSendFrom != value))
			{
				this.OnEmailSendFromChanging(value);
				this.SendPropertyChanging();
				this._EmailSendFrom = value;
				this.SendPropertyChanged("EmailSendFrom");
				this.OnEmailSendFromChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Image", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary Image
	{
		get
		{
			return this._Image;
		}
		set
		{
			if ((this._Image != value))
			{
				this.OnImageChanging(value);
				this.SendPropertyChanging();
				this._Image = value;
				this.SendPropertyChanged("Image");
				this.OnImageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
	public string Username
	{
		get
		{
			return this._Username;
		}
		set
		{
			if ((this._Username != value))
			{
				this.OnUsernameChanging(value);
				this.SendPropertyChanging();
				this._Username = value;
				this.SendPropertyChanged("Username");
				this.OnUsernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
	public string Password
	{
		get
		{
			return this._Password;
		}
		set
		{
			if ((this._Password != value))
			{
				this.OnPasswordChanging(value);
				this.SendPropertyChanging();
				this._Password = value;
				this.SendPropertyChanged("Password");
				this.OnPasswordChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="Jp.appliedJob")]
public partial class appliedJob : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private int _jobSeekerId;
	
	private int _jobid;
	
	private System.DateTime _date;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnjobSeekerIdChanging(int value);
    partial void OnjobSeekerIdChanged();
    partial void OnjobidChanging(int value);
    partial void OnjobidChanged();
    partial void OndateChanging(System.DateTime value);
    partial void OndateChanged();
    #endregion
	
	public appliedJob()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobSeekerId", DbType="Int NOT NULL")]
	public int jobSeekerId
	{
		get
		{
			return this._jobSeekerId;
		}
		set
		{
			if ((this._jobSeekerId != value))
			{
				this.OnjobSeekerIdChanging(value);
				this.SendPropertyChanging();
				this._jobSeekerId = value;
				this.SendPropertyChanged("jobSeekerId");
				this.OnjobSeekerIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobid", DbType="Int NOT NULL")]
	public int jobid
	{
		get
		{
			return this._jobid;
		}
		set
		{
			if ((this._jobid != value))
			{
				this.OnjobidChanging(value);
				this.SendPropertyChanging();
				this._jobid = value;
				this.SendPropertyChanged("jobid");
				this.OnjobidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date", DbType="DateTime NOT NULL")]
	public System.DateTime date
	{
		get
		{
			return this._date;
		}
		set
		{
			if ((this._date != value))
			{
				this.OndateChanging(value);
				this.SendPropertyChanging();
				this._date = value;
				this.SendPropertyChanged("date");
				this.OndateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="Jp.catagory")]
public partial class catagory : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _catagoryName;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncatagoryNameChanging(string value);
    partial void OncatagoryNameChanged();
    #endregion
	
	public catagory()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_catagoryName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string catagoryName
	{
		get
		{
			return this._catagoryName;
		}
		set
		{
			if ((this._catagoryName != value))
			{
				this.OncatagoryNameChanging(value);
				this.SendPropertyChanging();
				this._catagoryName = value;
				this.SendPropertyChanged("catagoryName");
				this.OncatagoryNameChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="Jp.feeds")]
public partial class feed : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _shortDescription;
	
	private string _longDescription;
	
	private System.Data.Linq.Binary _image;
	
	private System.Nullable<System.DateTime> _feedstartdate;
	
	private System.Nullable<System.DateTime> _feedenddate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnshortDescriptionChanging(string value);
    partial void OnshortDescriptionChanged();
    partial void OnlongDescriptionChanging(string value);
    partial void OnlongDescriptionChanged();
    partial void OnimageChanging(System.Data.Linq.Binary value);
    partial void OnimageChanged();
    partial void OnfeedstartdateChanging(System.Nullable<System.DateTime> value);
    partial void OnfeedstartdateChanged();
    partial void OnfeedenddateChanging(System.Nullable<System.DateTime> value);
    partial void OnfeedenddateChanged();
    #endregion
	
	public feed()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shortDescription", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string shortDescription
	{
		get
		{
			return this._shortDescription;
		}
		set
		{
			if ((this._shortDescription != value))
			{
				this.OnshortDescriptionChanging(value);
				this.SendPropertyChanging();
				this._shortDescription = value;
				this.SendPropertyChanged("shortDescription");
				this.OnshortDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_longDescription", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string longDescription
	{
		get
		{
			return this._longDescription;
		}
		set
		{
			if ((this._longDescription != value))
			{
				this.OnlongDescriptionChanging(value);
				this.SendPropertyChanging();
				this._longDescription = value;
				this.SendPropertyChanged("longDescription");
				this.OnlongDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary image
	{
		get
		{
			return this._image;
		}
		set
		{
			if ((this._image != value))
			{
				this.OnimageChanging(value);
				this.SendPropertyChanging();
				this._image = value;
				this.SendPropertyChanged("image");
				this.OnimageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_feedstartdate", DbType="DateTime")]
	public System.Nullable<System.DateTime> feedstartdate
	{
		get
		{
			return this._feedstartdate;
		}
		set
		{
			if ((this._feedstartdate != value))
			{
				this.OnfeedstartdateChanging(value);
				this.SendPropertyChanging();
				this._feedstartdate = value;
				this.SendPropertyChanged("feedstartdate");
				this.OnfeedstartdateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_feedenddate", DbType="DateTime")]
	public System.Nullable<System.DateTime> feedenddate
	{
		get
		{
			return this._feedenddate;
		}
		set
		{
			if ((this._feedenddate != value))
			{
				this.OnfeedenddateChanging(value);
				this.SendPropertyChanging();
				this._feedenddate = value;
				this.SendPropertyChanged("feedenddate");
				this.OnfeedenddateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="Jp.jobs")]
public partial class job : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private int _rId;
	
	private string _jobTitle;
	
	private string _description;
	
	private string _expectedSalary;
	
	private System.DateTime _postedDate;
	
	private string _country;
	
	private string _city;
	
	private string _jobCatagory;
	
	private string _salaryPeriod;
	
	private System.DateTime _lastDateToApply;
	
	private string _minimumEducation;
	
	private string _minimumLevelOfExperience;
	
	private string _specificRequirement;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnrIdChanging(int value);
    partial void OnrIdChanged();
    partial void OnjobTitleChanging(string value);
    partial void OnjobTitleChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void OnexpectedSalaryChanging(string value);
    partial void OnexpectedSalaryChanged();
    partial void OnpostedDateChanging(System.DateTime value);
    partial void OnpostedDateChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OncityChanging(string value);
    partial void OncityChanged();
    partial void OnjobCatagoryChanging(string value);
    partial void OnjobCatagoryChanged();
    partial void OnsalaryPeriodChanging(string value);
    partial void OnsalaryPeriodChanged();
    partial void OnlastDateToApplyChanging(System.DateTime value);
    partial void OnlastDateToApplyChanged();
    partial void OnminimumEducationChanging(string value);
    partial void OnminimumEducationChanged();
    partial void OnminimumLevelOfExperienceChanging(string value);
    partial void OnminimumLevelOfExperienceChanged();
    partial void OnspecificRequirementChanging(string value);
    partial void OnspecificRequirementChanged();
    #endregion
	
	public job()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rId", DbType="Int NOT NULL")]
	public int rId
	{
		get
		{
			return this._rId;
		}
		set
		{
			if ((this._rId != value))
			{
				this.OnrIdChanging(value);
				this.SendPropertyChanging();
				this._rId = value;
				this.SendPropertyChanged("rId");
				this.OnrIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobTitle", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string jobTitle
	{
		get
		{
			return this._jobTitle;
		}
		set
		{
			if ((this._jobTitle != value))
			{
				this.OnjobTitleChanging(value);
				this.SendPropertyChanging();
				this._jobTitle = value;
				this.SendPropertyChanged("jobTitle");
				this.OnjobTitleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
	public string description
	{
		get
		{
			return this._description;
		}
		set
		{
			if ((this._description != value))
			{
				this.OndescriptionChanging(value);
				this.SendPropertyChanging();
				this._description = value;
				this.SendPropertyChanged("description");
				this.OndescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_expectedSalary", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string expectedSalary
	{
		get
		{
			return this._expectedSalary;
		}
		set
		{
			if ((this._expectedSalary != value))
			{
				this.OnexpectedSalaryChanging(value);
				this.SendPropertyChanging();
				this._expectedSalary = value;
				this.SendPropertyChanged("expectedSalary");
				this.OnexpectedSalaryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_postedDate", DbType="DateTime NOT NULL")]
	public System.DateTime postedDate
	{
		get
		{
			return this._postedDate;
		}
		set
		{
			if ((this._postedDate != value))
			{
				this.OnpostedDateChanging(value);
				this.SendPropertyChanging();
				this._postedDate = value;
				this.SendPropertyChanged("postedDate");
				this.OnpostedDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string country
	{
		get
		{
			return this._country;
		}
		set
		{
			if ((this._country != value))
			{
				this.OncountryChanging(value);
				this.SendPropertyChanging();
				this._country = value;
				this.SendPropertyChanged("country");
				this.OncountryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_city", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string city
	{
		get
		{
			return this._city;
		}
		set
		{
			if ((this._city != value))
			{
				this.OncityChanging(value);
				this.SendPropertyChanging();
				this._city = value;
				this.SendPropertyChanged("city");
				this.OncityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobCatagory", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string jobCatagory
	{
		get
		{
			return this._jobCatagory;
		}
		set
		{
			if ((this._jobCatagory != value))
			{
				this.OnjobCatagoryChanging(value);
				this.SendPropertyChanging();
				this._jobCatagory = value;
				this.SendPropertyChanged("jobCatagory");
				this.OnjobCatagoryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_salaryPeriod", DbType="NVarChar(25)")]
	public string salaryPeriod
	{
		get
		{
			return this._salaryPeriod;
		}
		set
		{
			if ((this._salaryPeriod != value))
			{
				this.OnsalaryPeriodChanging(value);
				this.SendPropertyChanging();
				this._salaryPeriod = value;
				this.SendPropertyChanged("salaryPeriod");
				this.OnsalaryPeriodChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastDateToApply", DbType="DateTime NOT NULL")]
	public System.DateTime lastDateToApply
	{
		get
		{
			return this._lastDateToApply;
		}
		set
		{
			if ((this._lastDateToApply != value))
			{
				this.OnlastDateToApplyChanging(value);
				this.SendPropertyChanging();
				this._lastDateToApply = value;
				this.SendPropertyChanged("lastDateToApply");
				this.OnlastDateToApplyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minimumEducation", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string minimumEducation
	{
		get
		{
			return this._minimumEducation;
		}
		set
		{
			if ((this._minimumEducation != value))
			{
				this.OnminimumEducationChanging(value);
				this.SendPropertyChanging();
				this._minimumEducation = value;
				this.SendPropertyChanged("minimumEducation");
				this.OnminimumEducationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_minimumLevelOfExperience", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
	public string minimumLevelOfExperience
	{
		get
		{
			return this._minimumLevelOfExperience;
		}
		set
		{
			if ((this._minimumLevelOfExperience != value))
			{
				this.OnminimumLevelOfExperienceChanging(value);
				this.SendPropertyChanging();
				this._minimumLevelOfExperience = value;
				this.SendPropertyChanged("minimumLevelOfExperience");
				this.OnminimumLevelOfExperienceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specificRequirement", DbType="NVarChar(50)")]
	public string specificRequirement
	{
		get
		{
			return this._specificRequirement;
		}
		set
		{
			if ((this._specificRequirement != value))
			{
				this.OnspecificRequirementChanging(value);
				this.SendPropertyChanging();
				this._specificRequirement = value;
				this.SendPropertyChanged("specificRequirement");
				this.OnspecificRequirementChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="Jp.jobSeeker")]
public partial class jobSeeker : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _firstName;
	
	private string _lastName;
	
	private string _mobile;
	
	private string _email;
	
	private string _sex;
	
	private string _education;
	
	private string _country;
	
	private string _dob;
	
	private string _username;
	
	private string _password;
	
	private System.Data.Linq.Binary _image;
	
	private System.Nullable<System.DateTime> _signupdate;
	
	private System.Data.Linq.Binary _Status;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnfirstNameChanging(string value);
    partial void OnfirstNameChanged();
    partial void OnlastNameChanging(string value);
    partial void OnlastNameChanged();
    partial void OnmobileChanging(string value);
    partial void OnmobileChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnsexChanging(string value);
    partial void OnsexChanged();
    partial void OneducationChanging(string value);
    partial void OneducationChanged();
    partial void OncountryChanging(string value);
    partial void OncountryChanged();
    partial void OndobChanging(string value);
    partial void OndobChanged();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnimageChanging(System.Data.Linq.Binary value);
    partial void OnimageChanged();
    partial void OnsignupdateChanging(System.Nullable<System.DateTime> value);
    partial void OnsignupdateChanged();
    partial void OnStatusChanging(System.Data.Linq.Binary value);
    partial void OnStatusChanged();
    #endregion
	
	public jobSeeker()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_firstName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string firstName
	{
		get
		{
			return this._firstName;
		}
		set
		{
			if ((this._firstName != value))
			{
				this.OnfirstNameChanging(value);
				this.SendPropertyChanging();
				this._firstName = value;
				this.SendPropertyChanged("firstName");
				this.OnfirstNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lastName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string lastName
	{
		get
		{
			return this._lastName;
		}
		set
		{
			if ((this._lastName != value))
			{
				this.OnlastNameChanging(value);
				this.SendPropertyChanging();
				this._lastName = value;
				this.SendPropertyChanged("lastName");
				this.OnlastNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mobile", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string mobile
	{
		get
		{
			return this._mobile;
		}
		set
		{
			if ((this._mobile != value))
			{
				this.OnmobileChanging(value);
				this.SendPropertyChanging();
				this._mobile = value;
				this.SendPropertyChanged("mobile");
				this.OnmobileChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
	public string sex
	{
		get
		{
			return this._sex;
		}
		set
		{
			if ((this._sex != value))
			{
				this.OnsexChanging(value);
				this.SendPropertyChanging();
				this._sex = value;
				this.SendPropertyChanged("sex");
				this.OnsexChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_education", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
	public string education
	{
		get
		{
			return this._education;
		}
		set
		{
			if ((this._education != value))
			{
				this.OneducationChanging(value);
				this.SendPropertyChanging();
				this._education = value;
				this.SendPropertyChanged("education");
				this.OneducationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_country", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string country
	{
		get
		{
			return this._country;
		}
		set
		{
			if ((this._country != value))
			{
				this.OncountryChanging(value);
				this.SendPropertyChanging();
				this._country = value;
				this.SendPropertyChanged("country");
				this.OncountryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dob", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
	public string dob
	{
		get
		{
			return this._dob;
		}
		set
		{
			if ((this._dob != value))
			{
				this.OndobChanging(value);
				this.SendPropertyChanging();
				this._dob = value;
				this.SendPropertyChanged("dob");
				this.OndobChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string username
	{
		get
		{
			return this._username;
		}
		set
		{
			if ((this._username != value))
			{
				this.OnusernameChanging(value);
				this.SendPropertyChanging();
				this._username = value;
				this.SendPropertyChanged("username");
				this.OnusernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary image
	{
		get
		{
			return this._image;
		}
		set
		{
			if ((this._image != value))
			{
				this.OnimageChanging(value);
				this.SendPropertyChanging();
				this._image = value;
				this.SendPropertyChanged("image");
				this.OnimageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_signupdate", DbType="DateTime")]
	public System.Nullable<System.DateTime> signupdate
	{
		get
		{
			return this._signupdate;
		}
		set
		{
			if ((this._signupdate != value))
			{
				this.OnsignupdateChanging(value);
				this.SendPropertyChanging();
				this._signupdate = value;
				this.SendPropertyChanged("signupdate");
				this.OnsignupdateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarBinary(15)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="Jp.jobseekereducationalInfo")]
public partial class jobseekereducationalInfo : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private int _jobSeekerId;
	
	private string _instituteName;
	
	private System.DateTime _passingOutYear;
	
	private string _degreeName;
	
	private string _specialization;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnjobSeekerIdChanging(int value);
    partial void OnjobSeekerIdChanged();
    partial void OninstituteNameChanging(string value);
    partial void OninstituteNameChanged();
    partial void OnpassingOutYearChanging(System.DateTime value);
    partial void OnpassingOutYearChanged();
    partial void OndegreeNameChanging(string value);
    partial void OndegreeNameChanged();
    partial void OnspecializationChanging(string value);
    partial void OnspecializationChanged();
    #endregion
	
	public jobseekereducationalInfo()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobSeekerId", DbType="Int NOT NULL")]
	public int jobSeekerId
	{
		get
		{
			return this._jobSeekerId;
		}
		set
		{
			if ((this._jobSeekerId != value))
			{
				this.OnjobSeekerIdChanging(value);
				this.SendPropertyChanging();
				this._jobSeekerId = value;
				this.SendPropertyChanged("jobSeekerId");
				this.OnjobSeekerIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_instituteName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string instituteName
	{
		get
		{
			return this._instituteName;
		}
		set
		{
			if ((this._instituteName != value))
			{
				this.OninstituteNameChanging(value);
				this.SendPropertyChanging();
				this._instituteName = value;
				this.SendPropertyChanged("instituteName");
				this.OninstituteNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_passingOutYear", DbType="Date NOT NULL")]
	public System.DateTime passingOutYear
	{
		get
		{
			return this._passingOutYear;
		}
		set
		{
			if ((this._passingOutYear != value))
			{
				this.OnpassingOutYearChanging(value);
				this.SendPropertyChanging();
				this._passingOutYear = value;
				this.SendPropertyChanged("passingOutYear");
				this.OnpassingOutYearChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_degreeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string degreeName
	{
		get
		{
			return this._degreeName;
		}
		set
		{
			if ((this._degreeName != value))
			{
				this.OndegreeNameChanging(value);
				this.SendPropertyChanging();
				this._degreeName = value;
				this.SendPropertyChanged("degreeName");
				this.OndegreeNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specialization", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string specialization
	{
		get
		{
			return this._specialization;
		}
		set
		{
			if ((this._specialization != value))
			{
				this.OnspecializationChanging(value);
				this.SendPropertyChanging();
				this._specialization = value;
				this.SendPropertyChanged("specialization");
				this.OnspecializationChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="Jp.jobSeekerProfessionalInfo")]
public partial class jobSeekerProfessionalInfo : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private int _jobSeekerId;
	
	private string _experience;
	
	private System.Nullable<System.DateTime> _jobStartDate;
	
	private System.Nullable<System.DateTime> _jobEndDate;
	
	private string _company;
	
	private string _jobDescription;
	
	private string _workExperience;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnjobSeekerIdChanging(int value);
    partial void OnjobSeekerIdChanged();
    partial void OnexperienceChanging(string value);
    partial void OnexperienceChanged();
    partial void OnjobStartDateChanging(System.Nullable<System.DateTime> value);
    partial void OnjobStartDateChanged();
    partial void OnjobEndDateChanging(System.Nullable<System.DateTime> value);
    partial void OnjobEndDateChanged();
    partial void OncompanyChanging(string value);
    partial void OncompanyChanged();
    partial void OnjobDescriptionChanging(string value);
    partial void OnjobDescriptionChanged();
    partial void OnworkExperienceChanging(string value);
    partial void OnworkExperienceChanged();
    #endregion
	
	public jobSeekerProfessionalInfo()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobSeekerId", DbType="Int NOT NULL")]
	public int jobSeekerId
	{
		get
		{
			return this._jobSeekerId;
		}
		set
		{
			if ((this._jobSeekerId != value))
			{
				this.OnjobSeekerIdChanging(value);
				this.SendPropertyChanging();
				this._jobSeekerId = value;
				this.SendPropertyChanged("jobSeekerId");
				this.OnjobSeekerIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_experience", DbType="NVarChar(MAX)")]
	public string experience
	{
		get
		{
			return this._experience;
		}
		set
		{
			if ((this._experience != value))
			{
				this.OnexperienceChanging(value);
				this.SendPropertyChanging();
				this._experience = value;
				this.SendPropertyChanged("experience");
				this.OnexperienceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobStartDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> jobStartDate
	{
		get
		{
			return this._jobStartDate;
		}
		set
		{
			if ((this._jobStartDate != value))
			{
				this.OnjobStartDateChanging(value);
				this.SendPropertyChanging();
				this._jobStartDate = value;
				this.SendPropertyChanged("jobStartDate");
				this.OnjobStartDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobEndDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> jobEndDate
	{
		get
		{
			return this._jobEndDate;
		}
		set
		{
			if ((this._jobEndDate != value))
			{
				this.OnjobEndDateChanging(value);
				this.SendPropertyChanging();
				this._jobEndDate = value;
				this.SendPropertyChanged("jobEndDate");
				this.OnjobEndDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_company", DbType="NVarChar(50)")]
	public string company
	{
		get
		{
			return this._company;
		}
		set
		{
			if ((this._company != value))
			{
				this.OncompanyChanging(value);
				this.SendPropertyChanging();
				this._company = value;
				this.SendPropertyChanged("company");
				this.OncompanyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobDescription", DbType="NVarChar(50)")]
	public string jobDescription
	{
		get
		{
			return this._jobDescription;
		}
		set
		{
			if ((this._jobDescription != value))
			{
				this.OnjobDescriptionChanging(value);
				this.SendPropertyChanging();
				this._jobDescription = value;
				this.SendPropertyChanged("jobDescription");
				this.OnjobDescriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_workExperience", DbType="NVarChar(50)")]
	public string workExperience
	{
		get
		{
			return this._workExperience;
		}
		set
		{
			if ((this._workExperience != value))
			{
				this.OnworkExperienceChanging(value);
				this.SendPropertyChanging();
				this._workExperience = value;
				this.SendPropertyChanged("workExperience");
				this.OnworkExperienceChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="Jp.recruiter")]
public partial class recruiter : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _companyName;
	
	private System.DateTime _yearOfEstablishment;
	
	private string _briefProfile;
	
	private string _contactPerson;
	
	private string _phone;
	
	private string _fax;
	
	private string _email;
	
	private string _website;
	
	private string _emailVerification;
	
	private string _userName;
	
	private string _password;
	
	private System.Data.Linq.Binary _logo;
	
	private System.Nullable<System.DateTime> _signupdate;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OncompanyNameChanging(string value);
    partial void OncompanyNameChanged();
    partial void OnyearOfEstablishmentChanging(System.DateTime value);
    partial void OnyearOfEstablishmentChanged();
    partial void OnbriefProfileChanging(string value);
    partial void OnbriefProfileChanged();
    partial void OncontactPersonChanging(string value);
    partial void OncontactPersonChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnfaxChanging(string value);
    partial void OnfaxChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnwebsiteChanging(string value);
    partial void OnwebsiteChanged();
    partial void OnemailVerificationChanging(string value);
    partial void OnemailVerificationChanged();
    partial void OnuserNameChanging(string value);
    partial void OnuserNameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnlogoChanging(System.Data.Linq.Binary value);
    partial void OnlogoChanged();
    partial void OnsignupdateChanging(System.Nullable<System.DateTime> value);
    partial void OnsignupdateChanged();
    #endregion
	
	public recruiter()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_companyName", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
	public string companyName
	{
		get
		{
			return this._companyName;
		}
		set
		{
			if ((this._companyName != value))
			{
				this.OncompanyNameChanging(value);
				this.SendPropertyChanging();
				this._companyName = value;
				this.SendPropertyChanged("companyName");
				this.OncompanyNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yearOfEstablishment", DbType="DateTime NOT NULL")]
	public System.DateTime yearOfEstablishment
	{
		get
		{
			return this._yearOfEstablishment;
		}
		set
		{
			if ((this._yearOfEstablishment != value))
			{
				this.OnyearOfEstablishmentChanging(value);
				this.SendPropertyChanging();
				this._yearOfEstablishment = value;
				this.SendPropertyChanged("yearOfEstablishment");
				this.OnyearOfEstablishmentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_briefProfile", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
	public string briefProfile
	{
		get
		{
			return this._briefProfile;
		}
		set
		{
			if ((this._briefProfile != value))
			{
				this.OnbriefProfileChanging(value);
				this.SendPropertyChanging();
				this._briefProfile = value;
				this.SendPropertyChanged("briefProfile");
				this.OnbriefProfileChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_contactPerson", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string contactPerson
	{
		get
		{
			return this._contactPerson;
		}
		set
		{
			if ((this._contactPerson != value))
			{
				this.OncontactPersonChanging(value);
				this.SendPropertyChanging();
				this._contactPerson = value;
				this.SendPropertyChanged("contactPerson");
				this.OncontactPersonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string phone
	{
		get
		{
			return this._phone;
		}
		set
		{
			if ((this._phone != value))
			{
				this.OnphoneChanging(value);
				this.SendPropertyChanging();
				this._phone = value;
				this.SendPropertyChanged("phone");
				this.OnphoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fax", DbType="VarChar(20)")]
	public string fax
	{
		get
		{
			return this._fax;
		}
		set
		{
			if ((this._fax != value))
			{
				this.OnfaxChanging(value);
				this.SendPropertyChanging();
				this._fax = value;
				this.SendPropertyChanged("fax");
				this.OnfaxChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_website", DbType="VarChar(50)")]
	public string website
	{
		get
		{
			return this._website;
		}
		set
		{
			if ((this._website != value))
			{
				this.OnwebsiteChanging(value);
				this.SendPropertyChanging();
				this._website = value;
				this.SendPropertyChanged("website");
				this.OnwebsiteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emailVerification", DbType="VarChar(50)")]
	public string emailVerification
	{
		get
		{
			return this._emailVerification;
		}
		set
		{
			if ((this._emailVerification != value))
			{
				this.OnemailVerificationChanging(value);
				this.SendPropertyChanging();
				this._emailVerification = value;
				this.SendPropertyChanged("emailVerification");
				this.OnemailVerificationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userName", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string userName
	{
		get
		{
			return this._userName;
		}
		set
		{
			if ((this._userName != value))
			{
				this.OnuserNameChanging(value);
				this.SendPropertyChanging();
				this._userName = value;
				this.SendPropertyChanged("userName");
				this.OnuserNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string password
	{
		get
		{
			return this._password;
		}
		set
		{
			if ((this._password != value))
			{
				this.OnpasswordChanging(value);
				this.SendPropertyChanging();
				this._password = value;
				this.SendPropertyChanged("password");
				this.OnpasswordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_logo", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary logo
	{
		get
		{
			return this._logo;
		}
		set
		{
			if ((this._logo != value))
			{
				this.OnlogoChanging(value);
				this.SendPropertyChanging();
				this._logo = value;
				this.SendPropertyChanged("logo");
				this.OnlogoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_signupdate", DbType="DateTime")]
	public System.Nullable<System.DateTime> signupdate
	{
		get
		{
			return this._signupdate;
		}
		set
		{
			if ((this._signupdate != value))
			{
				this.OnsignupdateChanging(value);
				this.SendPropertyChanging();
				this._signupdate = value;
				this.SendPropertyChanged("signupdate");
				this.OnsignupdateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="Jp.skillsandcv")]
public partial class skillsandcv : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private int _jobSeekerid;
	
	private string _skills;
	
	private System.Data.Linq.Binary _cv_;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnjobSeekeridChanging(int value);
    partial void OnjobSeekeridChanged();
    partial void OnskillsChanging(string value);
    partial void OnskillsChanged();
    partial void Oncv_Changing(System.Data.Linq.Binary value);
    partial void Oncv_Changed();
    #endregion
	
	public skillsandcv()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jobSeekerid", DbType="Int NOT NULL")]
	public int jobSeekerid
	{
		get
		{
			return this._jobSeekerid;
		}
		set
		{
			if ((this._jobSeekerid != value))
			{
				this.OnjobSeekeridChanging(value);
				this.SendPropertyChanging();
				this._jobSeekerid = value;
				this.SendPropertyChanged("jobSeekerid");
				this.OnjobSeekeridChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_skills", DbType="VarChar(200)")]
	public string skills
	{
		get
		{
			return this._skills;
		}
		set
		{
			if ((this._skills != value))
			{
				this.OnskillsChanging(value);
				this.SendPropertyChanging();
				this._skills = value;
				this.SendPropertyChanged("skills");
				this.OnskillsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[cv`]", Storage="_cv_", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
	public System.Data.Linq.Binary cv_
	{
		get
		{
			return this._cv_;
		}
		set
		{
			if ((this._cv_ != value))
			{
				this.Oncv_Changing(value);
				this.SendPropertyChanging();
				this._cv_ = value;
				this.SendPropertyChanged("cv_");
				this.Oncv_Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
